/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author tauan
 */
public class CriarEmprestimo extends javax.swing.JFrame {
 
    /**
     * Creates new form CadastroFuncionario
     */
    public CriarEmprestimo() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDataEmprestimo = new javax.swing.JLabel();
        LabelDiaEmprestimo = new javax.swing.JLabel();
        EntryDiaEmprestimo = new javax.swing.JTextField();
        LabelMesEmprestimo = new javax.swing.JLabel();
        EntryMesEmprestimo = new javax.swing.JTextField();
        LabelAnoEmprestimo = new javax.swing.JLabel();
        EntryAnoEmprestimo = new javax.swing.JTextField();
        Barra1 = new javax.swing.JLabel();
        Barra2 = new javax.swing.JLabel();
        LabelCadastro = new javax.swing.JLabel();
        LabelFuncionarios = new javax.swing.JLabel();
        ScrollListaFunc = new javax.swing.JScrollPane();
        ListaFuncionarios = new javax.swing.JList<>();
        EntryFuncionarios = new javax.swing.JTextField();
        LabelEquipamentos = new javax.swing.JLabel();
        ScrollListaEquip = new javax.swing.JScrollPane();
        ListaEquipamentos = new javax.swing.JList<>();
        EntryEquip = new javax.swing.JTextField();
        LabelDataRetorno = new javax.swing.JLabel();
        LabelDiaRetorno = new javax.swing.JLabel();
        EntryDiaRetorno = new javax.swing.JTextField();
        LabelMesRetorno = new javax.swing.JLabel();
        EntryMesRetorno = new javax.swing.JTextField();
        LabelAnoRetorno = new javax.swing.JLabel();
        EntryAnoRetorno = new javax.swing.JTextField();
        Barra6 = new javax.swing.JLabel();
        Barra5 = new javax.swing.JLabel();
        BtAdicionar = new javax.swing.JButton();
        BtVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LabelDataEmprestimo.setText("Data do Emprestimo");

        LabelDiaEmprestimo.setText("Dia");

        EntryDiaEmprestimo.setPreferredSize(new java.awt.Dimension(40, 22));

        LabelMesEmprestimo.setText("Mês");

        EntryMesEmprestimo.setMaximumSize(new java.awt.Dimension(50, 22));
        EntryMesEmprestimo.setMinimumSize(new java.awt.Dimension(40, 22));
        EntryMesEmprestimo.setPreferredSize(new java.awt.Dimension(50, 22));
        EntryMesEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryMesEmprestimoActionPerformed(evt);
            }
        });

        LabelAnoEmprestimo.setText("Ano");

        EntryAnoEmprestimo.setMaximumSize(new java.awt.Dimension(50, 22));
        EntryAnoEmprestimo.setMinimumSize(new java.awt.Dimension(40, 22));
        EntryAnoEmprestimo.setPreferredSize(new java.awt.Dimension(50, 22));

        Barra1.setText("/");

        Barra2.setText("/");

        LabelCadastro.setText("Emprestimos");

        LabelFuncionarios.setText("Funcionarios disponiveis");

        ListaFuncionarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollListaFunc.setViewportView(ListaFuncionarios);

        EntryFuncionarios.setPreferredSize(new java.awt.Dimension(250, 22));

        LabelEquipamentos.setText("Equipamentos disponiveis");

        ListaEquipamentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ScrollListaEquip.setViewportView(ListaEquipamentos);

        EntryEquip.setPreferredSize(new java.awt.Dimension(250, 22));

        LabelDataRetorno.setText("Data Prevista para retorno");

        LabelDiaRetorno.setText("Dia");

        EntryDiaRetorno.setPreferredSize(new java.awt.Dimension(40, 22));

        LabelMesRetorno.setText("Mês");

        EntryMesRetorno.setMaximumSize(new java.awt.Dimension(50, 22));
        EntryMesRetorno.setMinimumSize(new java.awt.Dimension(40, 22));
        EntryMesRetorno.setPreferredSize(new java.awt.Dimension(50, 22));
        EntryMesRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryMesRetornoActionPerformed(evt);
            }
        });

        LabelAnoRetorno.setText("Ano");

        EntryAnoRetorno.setMaximumSize(new java.awt.Dimension(50, 22));
        EntryAnoRetorno.setMinimumSize(new java.awt.Dimension(40, 22));
        EntryAnoRetorno.setPreferredSize(new java.awt.Dimension(50, 22));

        Barra6.setText("/");

        Barra5.setText("/");

        BtAdicionar.setText("Adicionar");

        BtVoltar.setText("Voltar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDataEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDiaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EntryDiaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Barra2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EntryAnoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(LabelMesEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Barra1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EntryMesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(LabelAnoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelDataRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDiaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EntryDiaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Barra5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EntryAnoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(LabelMesRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Barra6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EntryMesRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(LabelAnoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntryFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(LabelFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(ScrollListaEquip))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ScrollListaFunc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntryEquip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelEquipamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EntryFuncionarios, LabelFuncionarios, ScrollListaEquip});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCadastro)
                    .addComponent(BtVoltar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDataEmprestimo)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDiaEmprestimo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LabelAnoEmprestimo)
                                            .addComponent(LabelMesEmprestimo))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EntryMesEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EntryAnoEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Barra1)
                                            .addComponent(Barra2)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EntryDiaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelDataRetorno)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelDiaRetorno)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(LabelAnoRetorno)
                                            .addComponent(LabelMesRetorno))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(EntryMesRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(EntryAnoRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Barra6)
                                            .addComponent(Barra5)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EntryDiaRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFuncionarios)
                    .addComponent(LabelEquipamentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollListaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ScrollListaEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntryEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtAdicionar))
                .addContainerGap())
        );

        LabelMesEmprestimo.getAccessibleContext().setAccessibleName("40");
        EntryMesEmprestimo.getAccessibleContext().setAccessibleName("40");
        LabelAnoEmprestimo.getAccessibleContext().setAccessibleName("40");
        EntryAnoEmprestimo.getAccessibleContext().setAccessibleName("40");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntryMesEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryMesEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryMesEmprestimoActionPerformed

    private void EntryMesRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryMesRetornoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryMesRetornoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barra1;
    private javax.swing.JLabel Barra2;
    private javax.swing.JLabel Barra5;
    private javax.swing.JLabel Barra6;
    private javax.swing.JButton BtAdicionar;
    private javax.swing.JButton BtVoltar;
    private javax.swing.JTextField EntryAnoEmprestimo;
    private javax.swing.JTextField EntryAnoRetorno;
    private javax.swing.JTextField EntryDiaEmprestimo;
    private javax.swing.JTextField EntryDiaRetorno;
    private javax.swing.JTextField EntryEquip;
    private javax.swing.JTextField EntryFuncionarios;
    private javax.swing.JTextField EntryMesEmprestimo;
    private javax.swing.JTextField EntryMesRetorno;
    private javax.swing.JLabel LabelAnoEmprestimo;
    private javax.swing.JLabel LabelAnoRetorno;
    private javax.swing.JLabel LabelCadastro;
    private javax.swing.JLabel LabelDataEmprestimo;
    private javax.swing.JLabel LabelDataRetorno;
    private javax.swing.JLabel LabelDiaEmprestimo;
    private javax.swing.JLabel LabelDiaRetorno;
    private javax.swing.JLabel LabelEquipamentos;
    private javax.swing.JLabel LabelFuncionarios;
    private javax.swing.JLabel LabelMesEmprestimo;
    private javax.swing.JLabel LabelMesRetorno;
    private javax.swing.JList<String> ListaEquipamentos;
    private javax.swing.JList<String> ListaFuncionarios;
    private javax.swing.JScrollPane ScrollListaEquip;
    private javax.swing.JScrollPane ScrollListaFunc;
    // End of variables declaration//GEN-END:variables
}
