/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package visao;

import controladores.MenuControll;
import controladores.ControladorFuncionario;
import java.time.LocalDate;
import javax.swing.JTextField;


/**
 *
 * @author tauan
 */
public class FormEquipamento extends javax.swing.JInternalFrame {
    Principal master;

    /**
     * Creates new form FormFuncionario
     */
    public FormEquipamento(Principal master) {
        initComponents();
        this.master = master;
        
    }
    
   public static LocalDate converterParaLocalDate(JTextField txtDia, JTextField txtMes, JTextField txtAno) {
        try {
            int dia = Integer.parseInt(txtDia.getText());
            int mes = Integer.parseInt(txtMes.getText());
            int ano = Integer.parseInt(txtAno.getText());


            // Validar a data (opcional)
            // ...

            return LocalDate.of(ano, mes, dia);
        } catch (NumberFormatException e) {
            System.err.println("Erro ao converter para LocalDate: " + e.getMessage());
            return LocalDate.of(2000, 1, 1); // Ou lançar uma exceção personalizada
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtSalvar = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LbDescricao = new javax.swing.JLabel();
        EntryDescricao = new javax.swing.JTextField();
        LbCargo = new javax.swing.JLabel();
        EntryPeso = new javax.swing.JTextField();
        LbDtAdmissao = new javax.swing.JLabel();
        EntryDtAdmissaoDia = new javax.swing.JFormattedTextField();
        LabelLargura = new javax.swing.JLabel();
        EntryLargura = new javax.swing.JTextField();
        LabelComprimento = new javax.swing.JLabel();
        EntryComprimento = new javax.swing.JTextField();
        LbEstado = new javax.swing.JLabel();
        LbDtAdmissao1 = new javax.swing.JLabel();
        EntryDtAdmissaoMes = new javax.swing.JFormattedTextField();
        LbDtAdmissao2 = new javax.swing.JLabel();
        LbDtAdmissao3 = new javax.swing.JLabel();
        EntryDtAdmissaoAno = new javax.swing.JFormattedTextField();
        jComboBox = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        BtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Atualizar.png"))); // NOI18N
        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Fechar.png"))); // NOI18N
        BtFechar.setText("Cancelar");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar)
                    .addComponent(BtFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        LbDescricao.setText("Descricao");

        EntryDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryDescricaoActionPerformed(evt);
            }
        });

        LbCargo.setText("Peso");

        EntryPeso.setMaximumSize(new java.awt.Dimension(50, 25));
        EntryPeso.setMinimumSize(new java.awt.Dimension(50, 25));
        EntryPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryPesoActionPerformed(evt);
            }
        });

        LbDtAdmissao.setText("Data de Admissão");

        LabelLargura.setText("Largura");

        EntryLargura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryLarguraActionPerformed(evt);
            }
        });

        LabelComprimento.setText("Comprimento");

        EntryComprimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryComprimentoActionPerformed(evt);
            }
        });

        LbEstado.setText("Estado");

        LbDtAdmissao1.setText("Dia");

        LbDtAdmissao2.setText("Mês");

        LbDtAdmissao3.setText("Ano");

        EntryDtAdmissaoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryDtAdmissaoAnoActionPerformed(evt);
            }
        });

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OTIMO", "BOM", "UTILIZAVEL", "QUEBRADO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntryDescricao)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(EntryComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EntryPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbCargo)
                    .addComponent(LabelLargura)
                    .addComponent(EntryLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbEstado)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LbDtAdmissao1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EntryDtAdmissaoDia))
                        .addComponent(LbDtAdmissao)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LbDtAdmissao2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EntryDtAdmissaoMes))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LbDtAdmissao3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EntryDtAdmissaoAno)))
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {EntryDescricao, LbDescricao});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDescricao)
                    .addComponent(LbDtAdmissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EntryDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EntryDtAdmissaoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LbDtAdmissao1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntryDtAdmissaoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbDtAdmissao2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntryDtAdmissaoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbDtAdmissao3))
                        .addGap(18, 18, 18)
                        .addComponent(LbEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LbCargo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntryPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLargura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntryLargura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelComprimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EntryComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        // TODO add your handling code here:
        

        master.equipamentoController.adicionarEquipamento(EntryDescricao.getText(), converterParaLocalDate(EntryDtAdmissaoDia,EntryDtAdmissaoMes,EntryDtAdmissaoAno), Integer.parseInt(EntryPeso.getText()),Integer.parseInt(EntryLargura.getText()),Integer.parseInt(EntryComprimento.getText()),jComboBox.getSelectedItem().toString());
        master.salvarDadosDeSer();
        master.atualizarListaEquip();
        this.dispose();
        

    }//GEN-LAST:event_BtSalvarActionPerformed

    private void EntryLarguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryLarguraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryLarguraActionPerformed

    private void EntryPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryPesoActionPerformed

    private void EntryDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryDescricaoActionPerformed

    private void EntryComprimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryComprimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryComprimentoActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void EntryDtAdmissaoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryDtAdmissaoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntryDtAdmissaoAnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JTextField EntryComprimento;
    private javax.swing.JTextField EntryDescricao;
    private javax.swing.JFormattedTextField EntryDtAdmissaoAno;
    private javax.swing.JFormattedTextField EntryDtAdmissaoDia;
    private javax.swing.JFormattedTextField EntryDtAdmissaoMes;
    private javax.swing.JTextField EntryLargura;
    private javax.swing.JTextField EntryPeso;
    private javax.swing.JLabel LabelComprimento;
    private javax.swing.JLabel LabelLargura;
    private javax.swing.JLabel LbCargo;
    private javax.swing.JLabel LbDescricao;
    private javax.swing.JLabel LbDtAdmissao;
    private javax.swing.JLabel LbDtAdmissao1;
    private javax.swing.JLabel LbDtAdmissao2;
    private javax.swing.JLabel LbDtAdmissao3;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
